22050
csv containts 8732 rows and 8 columns.
fold no_1 contains 873 audiofiles
fold no_2 contains 888 audiofiles
fold no_3 contains 925 audiofiles
fold no_4 contains 990 audiofiles
fold no_5 contains 936 audiofiles
fold no_6 contains 823 audiofiles
fold no_7 contains 838 audiofiles
fold no_8 contains 806 audiofiles
fold no_9 contains 816 audiofiles
fold no_10 contains 837 audiofiles
All in all there are 8732 audio files found in 8k Urban Sound dataset folders
Index(['slice_file_name', 'fsID', 'start', 'end', 'salience', 'fold',
       'classID', 'class'],
      dtype='object')


column <class> became... <Class>
['air_conditioner', 'car_horn', 'children_playing', 'dog_bark', 'drilling', 'engine_idling', 'gun_shot', 'jackhammer', 'siren', 'street_music']
loadin mel-spectograms..
features are loaded
cpu
model initialized...
attempt is already initialized
Experiment's _22050 attempt no_ : 1
Train started..

Epoch - 1 Train-Loss : 2.2936275506428645

Epoch - 1 Valid-Loss : 3.596244826058333
micro_f1_1 = 0.14575866188769415 
macro_f1_1 = 0.014989452972884542 

Epoch - 2 Train-Loss : 2.032313841632476

Epoch - 2 Valid-Loss : 3.864974139520254
micro_f1_2 = 0.13500597371565112 
macro_f1_2 = 0.015193946773801583 
Overfitting detected
Traceback (most recent call last):
  File "/mnt/scratch_a/users/m/melissap/code/exps/us8k/1.raw/main.py", line 100, in <module>
    train.train(model, loss_fn, train_loader, valid_loader, 
  File "/mnt/scratch_a/users/m/melissap/code/exps/us8k/1.raw/train.py", line 124, in train
    genres_filename = store.genres_filename(expid,mode,exp_attempt.get_attempt())
TypeError: genres_filename() takes 2 positional arguments but 3 were given
